# Generated by Django 5.2.13 on 2026-04-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultasVeterinariaPetcube',
            fields=[
                ('id_consulta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_consulta', models.DateTimeField()),
                ('motivo', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'consultas_veterinaria_petcube',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspeciesVeterinariaPetcube',
            fields=[
                ('id_especie', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_especie', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'especies_veterinaria_petcube',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MascotasVeterinariaPetcube',
            fields=[
                ('id_mascota', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'mascotas_veterinaria_petcube',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado'), ('cliente', 'Cliente')], default='cliente', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perfil_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RazasVeterinariaPetcube',
            fields=[
                ('id_raza', models.IntegerField(primary_key=True, serialize=False)),
                ('id_especie', models.IntegerField()),
                ('nombre_raza', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'razas_veterinaria_petcube',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VeterinariosVeterinariaPetcube',
            fields=[
                ('id_veterinario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'veterinarios_veterinaria_petcube',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientesVeterinariaPetcube',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('fecha_registro', models.DateField()),
                ('numero_documento', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'perfil_usuario',
                'managed': True,
            },
        ),
    ]
