# Generated by Django 5.2.13 on 2026-04-15 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={},
        ),
        migrations.AlterModelTable(
            name='clientesveterinariapetcube',
            table='clientes_veterinaria_petcube',
        ),
    ]
